# Generated by Django 4.0.4 on 2022-04-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=15, primary_key=True, serialize=False)),
                ('name_of_bank', models.CharField(blank=True, db_column='Name_of_bank', max_length=40, null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=30, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=10, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZipCode', max_length=6, null=True)),
                ('reservedassetvalue', models.IntegerField(blank=True, db_column='ReservedAssetValue', null=True)),
            ],
            options={
                'db_table': 'bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=15, primary_key=True, serialize=False)),
                ('shortname', models.CharField(blank=True, db_column='ShortName', max_length=20, null=True)),
                ('longname', models.CharField(blank=True, db_column='LongName', max_length=50, null=True)),
                ('reservedassetvalue', models.IntegerField(blank=True, db_column='ReservedAssetValue', null=True)),
            ],
            options={
                'db_table': 'corporation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=15, primary_key=True, serialize=False)),
                ('passwords', models.CharField(db_column='Passwords', max_length=20)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.person')),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('bank', models.OneToOneField(db_column='Bank_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.bank')),
                ('acc_id', models.CharField(db_column='Acc_ID', max_length=30)),
                ('balance', models.IntegerField(blank=True, db_column='Balance', null=True)),
            ],
            options={
                'db_table': 'bank_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.person')),
                ('joineddate', models.DateField(blank=True, db_column='JoinedDate', null=True)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=20, null=True)),
                ('ssn', models.CharField(blank=True, db_column='SSN', max_length=15, null=True)),
                ('dob', models.DateField(blank=True, db_column='DOB', null=True)),
                ('street', models.CharField(blank=True, db_column='Street', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=20, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=10, null=True)),
                ('zipcode', models.CharField(blank=True, db_column='ZipCode', max_length=6, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('bank', models.OneToOneField(db_column='Bank_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.bankaccount')),
            ],
            options={
                'db_table': 'checking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.users')),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.users')),
                ('monthlysalary', models.IntegerField(blank=True, db_column='MonthlySalary', null=True)),
                ('lifetimeearnings', models.IntegerField(blank=True, db_column='LifetimeEarnings', null=True)),
                ('numofpayments', models.IntegerField(blank=True, db_column='NumOfPayments', null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterestBearing',
            fields=[
                ('bank', models.OneToOneField(db_column='Bank_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.bankaccount')),
                ('last_deposit_date', models.DateField(blank=True, db_column='Last_deposit_date', null=True)),
                ('interest_rate', models.IntegerField(blank=True, db_column='Interest_rate', null=True)),
            ],
            options={
                'db_table': 'interest_bearing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountAccess',
            fields=[
                ('customer', models.OneToOneField(db_column='Customer_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.customer')),
                ('joined_date', models.DateField(blank=True, db_column='Joined_date', null=True)),
                ('last_transaction_date', models.DateField(blank=True, db_column='Last_transaction_date', null=True)),
            ],
            options={
                'db_table': 'account_access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountFees',
            fields=[
                ('bank', models.OneToOneField(db_column='Bank_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.interestbearing')),
                ('fee', models.CharField(db_column='Fee', max_length=20)),
            ],
            options={
                'db_table': 'account_fees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('customer', models.OneToOneField(db_column='Customer_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.customer')),
                ('type_of_contact', models.CharField(db_column='Type_of_contact', max_length=10)),
                ('address', models.CharField(db_column='Address', max_length=30)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('bank', models.OneToOneField(db_column='Bank_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.interestbearing')),
                ('num_withdrawals', models.IntegerField(blank=True, db_column='Num_withdrawals', null=True)),
                ('max_withdrawals', models.IntegerField(blank=True, db_column='Max_withdrawals', null=True)),
            ],
            options={
                'db_table': 'market',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('bank', models.OneToOneField(db_column='Bank_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.interestbearing')),
                ('min_balance', models.IntegerField(blank=True, db_column='Min_balance', null=True)),
                ('overdraft_date', models.DateField(blank=True, db_column='Overdraft_date', null=True)),
                ('overdraft_amount', models.IntegerField(blank=True, db_column='Overdraft_amount', null=True)),
            ],
            options={
                'db_table': 'saving',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkFor',
            fields=[
                ('bank_id', models.CharField(db_column='Bank_ID', max_length=15)),
                ('employee', models.OneToOneField(db_column='Employee_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.employee')),
            ],
            options={
                'db_table': 'work_for',
                'managed': False,
            },
        ),
    ]
