# Generated by Django 4.0.4 on 2022-04-17 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('bankid', models.OneToOneField(db_column='bankID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.bankaccount')),
                ('dtsharestart', models.DateField(db_column='dtShareStart')),
                ('dtaction', models.DateField(blank=True, db_column='dtAction', null=True)),
            ],
            options={
                'db_table': 'access',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankUser',
            fields=[
                ('perid', models.OneToOneField(db_column='perID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.person')),
                ('taxid', models.CharField(db_column='taxID', max_length=11, unique=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=100, null=True)),
                ('dtjoined', models.DateField(blank=True, db_column='dtJoined', null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'bank_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerContacts',
            fields=[
                ('perid', models.OneToOneField(db_column='perID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.customer')),
                ('contact_type', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'customer_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterestBearingFees',
            fields=[
                ('bankid', models.OneToOneField(db_column='bankID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.interestbearing')),
                ('fee', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'interest_bearing_fees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('bankid', models.OneToOneField(db_column='bankID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.interestbearing')),
                ('minbalance', models.IntegerField(blank=True, db_column='minBalance', null=True)),
            ],
            options={
                'db_table': 'savings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('perid', models.OneToOneField(db_column='perID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='bank.person')),
            ],
            options={
                'db_table': 'system_admin',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='accountaccess',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='accountfees',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='id',
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='customer',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AlterModelTable(
            name='workfor',
            table='workfor',
        ),
        migrations.DeleteModel(
            name='AccountAccess',
        ),
        migrations.DeleteModel(
            name='AccountFees',
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Saving',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
